main: dev.array21.harotorch.HaroTorch
name: HaroTorch-V2
author: TheDutchMC76
api-version: 1.16
description: HaroTorch is a plugin which adds the HaroTorch, a block which blocks mob spawns in a configurable radius.
softdepend: [Multiverse-Core]
version: @version@
commands:
 torch:
  description: Use /torch help for help
  usage: /torch <option>

permissions:
 harotorch.*:
  description: All HaroTorch v2 commands
  default: op
  children:
   harotorch.give: true
   harotorch.highlight: true
   harotorch.help: true
   harotorch.version: true
   harotorch.aoe: true
   harotorch.breakall: true
 harotorch.give:
  description: /torch give
  default: op
 harotorch.highlight:
  description: /torch highlight
  default: true
 harotorch.help:
  description: /torch help
  default: true
 harotorch.version:
  description: /torch version
  default: true
 harotorch.aoe:
  description: /torch aoe
  default: true
 harotorch.breakall:
  description: Allows a Player to break all torches
  default: false